/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服務健康檢查
         * @description 回報服務存活狀態與檢查時間，供部署探針與監控使用。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 服務正常 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /**
                                 * @description 存活訊號，恆為 ok（Redis 故障時服務仍持續供應、ingestion 走降級， 不因 Redis 翻轉本欄位）。
                                 * @example ok
                                 */
                                serviceStatus: string;
                                /**
                                 * @description Redis 連線探測結果（1 秒 ping 上限）：ok 正常、down 故障或逾時、 not_configured 未配置（in-memory/dev 模式）。
                                 * @example ok
                                 * @enum {string}
                                 */
                                redis: "ok" | "down" | "not_configured";
                                /** Format: date-time */
                                checkedAt: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 帳號登入
         * @description 使用帳號與密碼進行登入，回傳短效 access token（JWT）與長效 refresh token （opaque 隨機字串，非 JWT）。refresh token 僅能用於 /api/v1/auth/refresh 的 request body，嚴禁出現在任何 query 參數。此 API 錯誤訊息統一以降低帳號列舉攻擊風險。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example super_admin */
                        account: string;
                        /**
                         * Format: password
                         * @example password123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登入成功，回傳 access token 與 refresh token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["TokenPairData"];
                        };
                    };
                };
                /** @description 認證失敗，統一回傳「帳號或密碼錯誤」 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 換發 access token（refresh token rotation）
         * @description 以 refresh token 換發新的 access token 與 refresh token 一對（rotation： 舊 refresh token 作廢，新 token 生效並展期）。具 reuse detection：已被 rotate 的舊 token 於寬限期（30 秒，容忍多分頁併發刷新）外再次出現，視為 token 竊取，撤銷整個 token family，後續 refresh 一律 401。refresh token 僅能放在 request body，嚴禁出現在任何 query 參數。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description 換發成功，回傳新的 access token 與 refresh token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["TokenPairData"];
                        };
                    };
                };
                /** @description refresh token 無效、已過期、已撤銷或偵測到重用（reuse detection） */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 帳號登出
         * @description 登出並撤銷 refresh token：request body 帶 refreshToken 時，撤銷該 token 所屬的整個 token family（rotation 鏈），其後該 family 不可再換發。 access token 不做 blacklist，至自然到期前仍有效，前端收到 success 後自行丟棄。 不帶 body 仍回傳成功（向後相容既有前端）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refreshToken?: string;
                    };
                };
            };
            responses: {
                /** @description 登出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢當前登入者資訊
         * @description 以 Bearer JWT 取得當前認證主體的帳號資訊與角色，供前端在登入後補拉使用者資料。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** Format: uuid */
                                accountId: string;
                                /** @description 登入帳號 */
                                account: string;
                                /** @description 使用者姓名 */
                                name: string;
                                /**
                                 * @description 角色清單，現行值為 super_admin / observer
                                 * @example [
                                 *       "observer"
                                 *     ]
                                 */
                                roles: string[];
                            };
                        };
                    };
                };
                /** @description 未帶 token 或 token 無效/過期 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改或重設帳號密碼
         * @description observer 僅可修改自己的密碼，且必須提供現行密碼 oldPassword；super_admin 可重設他人密碼（免帶 oldPassword），但不得以此 API 變更自己的密碼。oldPassword 在規格上為 optional，「self 改密必填」屬 runtime 規則:observer 改自己時若未帶或帶錯 oldPassword 一律回 400 INVALID_OLD_PASSWORD。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: password
                         * @description 現行密碼。observer 改自己時必填;super_admin 重設他人密碼時免填。
                         */
                        oldPassword?: string;
                        /** Format: password */
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description 密碼修改成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description self 改密時舊密碼錯誤/未提供（errorCode：INVALID_OLD_PASSWORD） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description super_admin 不得以此 API 變更自己的密碼（errorCode：CANNOT_CHANGE_OWN_PASSWORD） */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description 輸入驗證失敗，如 newPassword 長度不符（errorCode：VALIDATION_ERROR） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢帳號列表
         * @description 取得系統內所有帳號，僅 super_admin 可操作。支援 page-based pagination。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["AccountResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 建立新帳號
         * @description 僅 super_admin 可操作。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 帳號唯一標識，即便 soft delete 後，此帳號名亦不可重複使用。 */
                        account: string;
                        /** Format: password */
                        password: string;
                        name: string;
                        /**
                         * @example [
                         *       "observer"
                         *     ]
                         */
                        roles: string[];
                    };
                };
            };
            responses: {
                /** @description 建立成功，回傳完整帳號資料 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AccountResponse"];
                        };
                    };
                };
                /** @description 帳號已存在（errorCode：ACCOUNT_ALREADY_EXISTS） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description 輸入驗證失敗，如密碼長度不符（errorCode：VALIDATION_ERROR） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢指定帳號詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AccountResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 軟刪除帳號
         * @description 僅 super_admin 可操作。限制：super_admin 不得刪除自己；亦不得刪除最後一個 active super_admin（errorCode：CANNOT_DELETE_LAST_SUPER_ADMIN，HTTP 409）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description 不得刪除最後一個 active super_admin（errorCode：CANNOT_DELETE_LAST_SUPER_ADMIN） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * 更新帳號資訊
         * @description 僅 super_admin 可更新他人資訊與角色。不得移除最後一個 active super_admin 的 super_admin 角色（errorCode：CANNOT_DOWNGRADE_LAST_SUPER_ADMIN，HTTP 409）。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /**
                         * @example [
                         *       "observer"
                         *     ]
                         */
                        roles?: string[];
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AccountResponse"];
                        };
                    };
                };
                /** @description 不得移除最後一個 active super_admin 的 super_admin 角色（errorCode：CANNOT_DOWNGRADE_LAST_SUPER_ADMIN） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢觀測點列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: (components["schemas"]["SiteResponse"] & {
                                    /**
                                     * @description 該隊未軟刪除觀測站數(僅列表回應提供)
                                     * @example 12
                                     */
                                    stationCount: number;
                                })[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 建立觀測點 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        siteName: string;
                    };
                };
            };
            responses: {
                /** @description 建立成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["SiteResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢指定觀測點詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["SiteResponse"];
                        };
                    };
                };
                /** @description 找不到該觀測點或已被刪除 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        /** 更新觀測點 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        siteName: string;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["SiteResponse"];
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * 刪除觀測點 (Cascade Soft Delete)
         * @description 軟刪除觀測點，並連帶軟刪除旗下的 Station、Watch 與 Sighting。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    siteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢觀測站列表
         * @description 取得觀測站列表，包含其所屬觀測點名稱。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                    /** @description 篩選指定觀測點 */
                    siteId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["StationResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 建立觀測站 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        stationName: string;
                        /** Format: uuid */
                        siteId: string;
                        stationCode: number;
                        /** @description 投打慣用手描述，任意字串，長度限制 100 個繁體中文字 */
                        mountType: string;
                        /**
                         * @description 觀測站緯度 (度)，為天球分區圖提供 observer_lat 參數
                         * @example 175.5
                         */
                        height: number;
                        /**
                         * @description 觀測站經度 (度)
                         * @example 70.2
                         */
                        weight: number;
                    };
                };
            };
            responses: {
                /** @description 建立成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["StationResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{stationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢指定觀測站詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["StationResponse"];
                        };
                    };
                };
            };
        };
        /** 更新觀測站資訊 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        stationName?: string;
                        /** Format: uuid */
                        siteId?: string;
                        stationCode?: number;
                        /** @description 投打慣用手描述，任意字串，長度限制 100 個繁體中文字 */
                        mountType?: string;
                        /** @description 緯度 (度) */
                        height?: number;
                        /** @description 經度 (度) */
                        weight?: number;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["StationResponse"];
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * 刪除觀測站 (Cascade Soft Delete)
         * @description 軟刪除觀測站，並連帶軟刪除該觀測站旗下的 Watch 與 Sighting。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢觀測時段列表
         * @description Page-based 分頁查詢觀測時段列表，依建立時間新到舊排序，排除已軟刪除的觀測時段。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["WatchResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 新增觀測時段
         * @description 僅能輸入觀測時段名稱、觀測點ID與觀測站ID。系統預設狀態為 `created`。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 20260529 英仙座雙站觀測 */
                        watchName: string;
                        /** Format: uuid */
                        siteId: string;
                        /** Format: uuid */
                        stationId: string;
                    };
                };
            };
            responses: {
                /** @description 建立成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["WatchResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watches/{watchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 刪除觀測時段 (Cascade Soft Delete)
         * @description 軟刪除觀測時段，並連帶軟刪除該時段產生的所有 Sighting 資料（影片與 Raw 暫存不刪除，但不再提供觀看）。 允許刪除 `inProgress` 的觀測時段；刪除屬資料層語意，不會呼叫外部 traj/photo 服務停止擷取—— 若需停止擷取請先呼叫 `/stop` 再刪除（MVP 決定）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description 找不到該觀測時段或已被刪除（errorCode：WATCH_NOT_FOUND） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watches/{watchId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 開始觀測時段
         * @description 將觀測時段狀態改為 `inProgress`。
         *     後端會呼叫外部 traj 與 photo 的 `/start` 端點。
         *     - 呼叫外部服務時，設有 5 秒 timeout，最多 retry 3 次。
         *     - 若任一外部服務失敗，則此 API 宣告失敗，狀態維持 `created`。
         *     - 同時間只允許有一場觀測時段處於 `inProgress` 狀態。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 觀測時段已成功啟動，狀態改為 inProgress */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["WatchResponse"];
                        };
                    };
                };
                /** @description 當前已有其他 inProgress 的觀測時段（errorCode：WATCH_ALREADY_IN_PROGRESS）， 或觀測時段狀態不符合啟動條件、非 created（errorCode：WATCH_NOT_IN_CREATED_STATE） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description 外部 traj 或 photo 服務啟動失敗 (Timeout 或呼叫失敗) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watches/{watchId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 結束觀測時段
         * @description 將觀測時段狀態改為 `ended`。
         *     後端會呼叫外部服務的 `/stop` 以停止接收感測器數據。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    watchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 觀測時段已結束，狀態改為 ended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["WatchResponse"];
                        };
                    };
                };
                /** @description 觀測時段非處於 inProgress 狀態（errorCode：WATCH_NOT_IN_PROGRESS） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watches/{watchId}/sightings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢指定觀測時段的目擊事件列表
         * @description 回傳該觀測時段的所有 Sighting 列表，依時間由新到舊排序。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path: {
                    watchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["SightingSummaryResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sightings/{sightingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢單筆詳情
         * @description 取得指定目擊事件的詳細 analysis 數據與影片 URL。
         *     - 影片檔(MP4) 直接由後端提供相對/絕對 URL，交由 Nginx 處理，不經由 API stream 二進位傳輸。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sightingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["SightingDetailResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 軟刪除指定單筆目擊事件資料
         * @description 單筆 soft delete。被刪目擊事件不再出現於列表、詳情、歷史查詢與 CSV 匯出。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sightingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description 找不到該目擊事件或已被刪除（errorCode：SIGHTING_NOT_FOUND） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sightings/{sightingId}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 收藏目擊事件
         * @description 標註該目擊事件為收藏。不需夾帶 watchId。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sightingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 收藏成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sightings/{sightingId}/unfavorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消收藏目擊事件
         * @description 取消該目擊事件的收藏。不需夾帶 watchId。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sightingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取消成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢有觀測時段的日期 (依年月)
         * @description 輸入年與月，回傳當月哪些日期有觀測時段記錄。
         */
        get: {
            parameters: {
                query: {
                    year: number;
                    month: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/daily-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢當日觀測時段與總目擊數
         * @description 輸入日期，回傳該日期所發生的觀測時段列表、各時段的觀測站，以及各時段的總目擊數。
         */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** Format: uuid */
                                watchId: string;
                                watchName: string;
                                /** Format: uuid */
                                siteId: string;
                                siteName: string;
                                /** Format: uuid */
                                stationId: string;
                                stationName: string;
                                /** @enum {string} */
                                status: "created" | "inProgress" | "ended";
                                /** @description 該場觀測時段的總目擊數 */
                                totalSightings: number;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description 日期格式錯誤（FastAPI 請求驗證，errorCode：VALIDATION_ERROR） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/daily-stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢當日有觀測的站點
         * @description 輸入日期，回傳當天有進行觀測的觀測站清單。
         */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** Format: uuid */
                                stationId: string;
                                stationName: string;
                                stationCode: number;
                                /** Format: uuid */
                                siteId: string;
                                siteName: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/sightings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 歷史目擊事件資料搜尋
         * @description 支援多條件複合篩選，取得歷史目擊事件的列表資料（分頁）。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 觀測站 ID 陣列 (可選) */
                    stationIds?: string[];
                    /** @description 查詢開始日期 (可選) */
                    startDate?: string;
                    /** @description 查詢結束日期 (可選) */
                    endDate?: string;
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["SightingHistorySummary"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/sightings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 依搜尋條件匯出 CSV
         * @description 同步匯出符合搜尋條件的目擊事件數據 CSV 檔。匯出列數上限為 50000;若符合條件的列數超過上限, 回 422(errorCode:EXPORT_TOO_LARGE),要求縮小日期或 stationIds 範圍,而非靜默截斷。 上限檢查在串流開始前以 count 預檢完成,故超限為 JSON 422 而非「截斷的 200」。
         */
        get: {
            parameters: {
                query?: {
                    stationIds?: string[];
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 匯出成功，同步回傳 CSV 內容 */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv; charset=utf-8": string;
                    };
                };
                /** @description 輸入不合法(stationIds 非 uuid),或符合條件的列數超過匯出上限 50000 (errorCode:EXPORT_TOO_LARGE)。為 JSON 錯誤,非截斷的 CSV。 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/sightings/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 依選定目擊事件 ID 匯出 CSV
         * @description 同步匯出選定 sightingId 清單的目擊事件數據 CSV 檔。sightingIds 數量上限為 50000(與 search 匯出共用同一上限);超過上限回 422(errorCode:EXPORT_TOO_LARGE),非截斷的 CSV。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sightingIds: string[];
                    };
                };
            };
            responses: {
                /** @description 匯出成功，同步回傳 CSV 內容 */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv; charset=utf-8": string;
                    };
                };
                /** @description sightingIds 含非 uuid 值,或數量超過上限 50000(errorCode:EXPORT_TOO_LARGE)。 為 JSON 錯誤,非截斷的 CSV。 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/{streamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢指定串流資訊
         * @description 查詢 DB 回傳 HLS playlist URLs 及當前串流狀態。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    streamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["StreamResponse"];
                        };
                    };
                };
                /** @description 找不到該串流資源 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢相機與串流狀態列表
         * @description 回傳環境中所有設定的 Camera 狀態。
         *     - 去除 legacy deviceId 欄位。
         *     - camera id 與位置由後端從 `.env` JSON 格式(CAMERAS v2:`cameraId`/`position`/`source`)解析。
         *     - `connectionStatus` 為即時狀態:後端背景輪詢上游(traj/photo `/status`+`/cameras`、
         *       recorder `/cameras`)寫入記憶體快取,本端點永遠讀快取秒回;
         *       首輪輪詢完成前一律回 `disconnected`。
         *     - 工業相機組(source 為 traj/photo)額外透傳 `captureStatus`(上游原始服務狀態,
         *       debug 線索);recorder 相機與上游不可達時「省略」該欄位(不以 null 佔位)。
         *     - recorder 相機額外帶 `streamId`(該相機直播 stream 的參照 id):前端以
         *       `/cameras` 取 `streamId` → `GET /streams/{streamId}` 取 `hlsUrl` 播放,
         *       毋須(也不應)client-side 推導。traj/photo 相機無直播,「省略」該欄位。
         *       `hlsUrl` 維持僅由 streams 端點提供(單一真相來源)。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** @example cam-01 */
                                cameraId: string;
                                /**
                                 * @description 相機架設方位
                                 * @example behind-home-plate
                                 */
                                position: string;
                                /**
                                 * @example connected
                                 * @enum {string}
                                 */
                                connectionStatus: "connected" | "disconnected" | "error";
                                /**
                                 * @description 工業相機組(traj/photo)上游原始服務狀態透傳,僅該組出現;
                                 *     recorder 相機與上游不可達時省略此欄位。
                                 * @example running
                                 * @enum {string}
                                 */
                                captureStatus?: "stopped" | "starting" | "running" | "stopping" | "error";
                                /**
                                 * Format: uuid
                                 * @description recorder 相機的直播 stream 參照 id;僅 source=recorder
                                 *     相機出現(traj/photo 省略,同 captureStatus 的 optional 慣例)。
                                 *     以此打 `GET /api/v1/streams/{streamId}` 取 `hlsUrl`。
                                 * @example 550e8400-e29b-41d4-a716-446655440000
                                 */
                                streamId?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 即時事件推播
         * @description 以 Server-Sent Events（`text/event-stream`）推播即時事件。
         *
         *     ### 認證
         *     原生 EventSource 無法夾帶 Authorization header，本端點改以 **`?token=<JWT>` query 參數**
         *     認證（同一 access token）。缺少或無效/過期 token 回 401。
         *     注意：token 會出現在反向代理 access log 與瀏覽器歷史，僅限短效 access token 使用。
         *
         *     ### 頻道訂閱與授權
         *     - 頻道命名：`account:{accountId}`（帳號個人頻道）、`watch:{watchId}`（觀測時段頻道）。
         *     - 連線**必訂自己的 `account:{accountId}` 頻道**（預設頻道，毋須指定）。
         *     - 可用 `?channels=` 以逗號分隔額外請求頻道，逐一過 RBAC 訂閱授權：
         *       `account:*` 僅允許訂自己；`watch:*` 需具 watches 讀取權限。
         *     - **無權限的頻道靜默剔除**（不擋整條連線）；實際訂閱結果以 `connected` 歡迎訊息的
         *       `data.channels` 為準。
         *
         *     ### 訊息格式
         *     每筆事件為一個 SSE `data:` 區塊，內容為 JSON 信封（見 `SseEventEnvelope`）：
         *     `{ id, type, channel, timestamp, data }`。事件類型（`type`）：
         *     - `connected`：連線歡迎訊息，`data: { "channels": [實際訂閱頻道] }`
         *     - `sightingCreated`：新目擊事件建立，`data: { "sightingId", "watchId" }`
         *     - `watchCaptureStarted` / `watchCaptureStopped`：觀測時段 AI 採集啟動/停止，`data: { "watchId" }`
         *
         *     ### 保活
         *     無訊息時每 **30 秒**送一行 SSE 註解 `: heartbeat` 維持連線（非 JSON 訊息，客戶端應忽略）。
         *     回應夾帶 `Cache-Control: no-cache`、`X-Accel-Buffering: no`（停用反向代理緩衝）。
         */
        get: {
            parameters: {
                query: {
                    /** @description JWT access token（取代 Authorization header） */
                    token: string;
                    /** @description 逗號分隔的額外訂閱頻道清單，例如 `watch:9a1f...,account:自己的accountId` */
                    channels?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 連線成功，開始推播事件串流（首筆為 `connected` 歡迎訊息） */
                200: {
                    headers: {
                        "Cache-Control"?: string;
                        "X-Accel-Buffering"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description 未帶 token 或 token 無效/過期 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traj-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 接收 traj 原始數據 (內網信任)
         * @description 由內網 traj 採集服務呼叫（v2 契約，#86，breaking：舊版毫秒整數 timestamp 格式回 422）。
         *     - 接收後端即時產生 UUID 作為 ID。
         *     - `timestamp` 為 naive 字串（UTC+8 牆鐘時間），轉為 UTC 儲存並進行 Redis 2秒配對。
         *     - 冪等重送：相同 `timestamp`（capture 時刻）視為同一筆目擊事件，回傳既有 `trajDataId`，
         *       不重複建立 raw 紀錄、不重複建立 sighting。
         *     - 完整原始 payload 以 JSONB 照存；裝置端附帶的舊版計算欄位（`path_trajectory`、
         *       `terminal_point`、`path_velocity`、`raw_traj_2d` 等）寬鬆接收、照存不拆欄。
         *     - 內網信任，不掛 JWT。
         *     - Payload 為外部 snake_case，在此處做防腐層轉換。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TrajRawPayload"];
                };
            };
            responses: {
                /** @description 數據接收並持久化成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /**
                             * Format: uuid
                             * @description 後端產生的 UUID
                             */
                            trajDataId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photo-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 接收 photo 原始數據 (內網信任)
         * @description 由內網 photo 採集服務呼叫（v2 契約，#86，breaking：舊版毫秒整數 timestamp 格式回 422）。
         *     - 接收後端即時產生 UUID 作為 ID。
         *     - `timestamp` 為 naive 字串（UTC+8 牆鐘時間），轉為 UTC 儲存。
         *     - 冪等重送：相同 `timestamp`（capture 時刻）視為同一筆目擊事件，回傳既有 `photoDataId`，
         *       不重複建立 raw 紀錄。
         *     - 將原始的 `radiant` 陣列拆為 `radiantX`, `radiantY`, `radiantZ` 存入資料庫；完整原始
         *       payload 以 JSONB 照存，額外欄位寬鬆接收。
         *     - 內網信任，不掛 JWT。
         *     - Payload 為外部 snake_case，在此處做防腐層轉換。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoRawPayload"];
                };
            };
            responses: {
                /** @description 數據接收並持久化成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /**
                             * Format: uuid
                             * @description 後端產生的 UUID
                             */
                            photoDataId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @example true */
            success: boolean;
            /** @example 操作成功 */
            message?: string;
            /** @description 成功回應的主體。基底不限定型別，由各端點以 allOf 特化為 object 或 array （回傳陣列的端點覆寫為 array，分頁端點請改用 PaginatedSuccessEnvelope）。 */
            data: unknown;
            /** @description 其他非分頁之元數據 */
            meta?: Record<string, never>;
        };
        PaginatedSuccessEnvelope: {
            /** @example true */
            success: boolean;
            data: {
                items: Record<string, never>[];
            };
            meta: {
                pagination: {
                    /** @example 1 */
                    page: number;
                    /** @example 20 */
                    pageSize: number;
                    /** @example 150 */
                    totalItems: number;
                    /** @example 8 */
                    totalPages: number;
                };
            };
        };
        ErrorEnvelope: {
            /** @example false */
            success: boolean;
            /**
             * @description CONSTANT_CASE 錯誤碼
             * @example RESOURCE_NOT_FOUND
             */
            code: string;
            /**
             * @description 提供給使用者閱讀的錯誤訊息
             * @example 找不到指定的資源
             */
            message: string;
            /** @description 欄位層級的驗證錯誤細節 (選填) */
            errors?: {
                /** @example stationCode */
                field: string;
                /** @example 必須為大於 0 的整數 */
                message: string;
            }[];
        };
        TokenPairData: {
            /**
             * @description Bearer JWT token（短效 access token）
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /**
             * Format: date-time
             * @description access token 到期時間
             */
            expiresAt: string;
            /** Format: uuid */
            accountId: string;
            /** @description opaque refresh token（非 JWT），僅能用於 /api/v1/auth/refresh 的 request body，嚴禁出現在任何 query 參數。 */
            refreshToken: string;
            /**
             * Format: date-time
             * @description refresh token 到期時間（rotation 時展期，sliding window）
             */
            refreshExpiresAt: string;
        };
        AccountResponse: {
            /** Format: uuid */
            accountId: string;
            /** @description 登入帳號 */
            account: string;
            /** @description 使用者姓名 */
            name: string;
            /**
             * @example [
             *       "observer"
             *     ]
             */
            roles: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SiteResponse: {
            /** Format: uuid */
            siteId: string;
            siteName: string;
            /** @example false */
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 軟刪除時間，未刪除為 null
             */
            deletedAt: string | null;
            /**
             * Format: uuid
             * @description 執行軟刪除的帳號，未刪除為 null
             */
            deletedByAccountId: string | null;
        };
        StationResponse: {
            /** Format: uuid */
            stationId: string;
            stationName: string;
            /** Format: uuid */
            siteId: string;
            /** @description 所屬觀測點名稱 */
            siteName: string;
            stationCode: number;
            /** @description 投打慣用手描述，任意字串，長度限制 100 個繁體中文字 */
            mountType: string;
            /** @description 緯度 (度) */
            height: number;
            /** @description 經度 (度) */
            weight: number;
            /** @example false */
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 軟刪除時間，未刪除為 null
             */
            deletedAt: string | null;
            /**
             * Format: uuid
             * @description 執行軟刪除的帳號，未刪除為 null
             */
            deletedByAccountId: string | null;
        };
        WatchResponse: {
            /** Format: uuid */
            watchId: string;
            watchName: string;
            /** Format: uuid */
            siteId: string;
            /** @description 所屬觀測點名稱。已軟刪除的觀測點仍解析名稱（比照歷史查詢 join 語意）。 */
            siteName: string;
            /** Format: uuid */
            stationId: string;
            /** @description 觀測站姓名。已軟刪除的觀測站仍解析名稱（比照歷史查詢 join 語意）。 */
            stationName: string;
            /** @enum {string} */
            status: "created" | "inProgress" | "ended";
            /**
             * Format: date-time
             * @description 觀測時段開始時間（/start 成功後寫入），未開始為 null
             */
            startedAt: string | null;
            /**
             * Format: date-time
             * @description 觀測時段結束時間（/stop 成功後寫入），未結束為 null
             */
            endedAt: string | null;
            /** @example false */
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 軟刪除時間，未刪除為 null
             */
            deletedAt: string | null;
            /**
             * Format: uuid
             * @description 執行軟刪除的帳號，未刪除為 null
             */
            deletedByAccountId: string | null;
        };
        SightingSummaryResponse: {
            /** Format: uuid */
            sightingId: string;
            /** Format: uuid */
            watchId: string;
            /**
             * @description 入射速度 (km/s)
             * @example 135.8
             */
            entrySpeed: number | null;
            /** @example false */
            isFavorite: boolean;
            /**
             * Format: date-time
             * @description 目擊事件時間戳記 (UTC)
             */
            timestamp: string;
        };
        SightingHistorySummary: {
            /** Format: uuid */
            sightingId: string;
            /** Format: uuid */
            watchId: string;
            watchName: string;
            /** Format: uuid */
            stationId: string;
            stationName: string;
            /** @description km/h */
            entrySpeed: number | null;
            isFavorite: boolean;
            /** Format: date-time */
            timestamp: string;
        };
        SightingDetailResponse: {
            /** Format: uuid */
            sightingId: string;
            /** Format: uuid */
            watchId: string;
            /**
             * @description 由分析產出的流星雨代碼，例如 PER, GEM, ORI, SPO（偶發）等。isTrajOnly=true（未配對）時無分析結果，為 null。
             * @example PER
             */
            showerCode: string | null;
            /**
             * @description 是否為未配對成功、僅有 traj 資料的目擊事件
             * @example false
             */
            isTrajOnly: boolean;
            isFavorite: boolean;
            /** Format: date-time */
            timestamp: string;
            /** @description 目擊事件分析數據。各欄位於 isTrajOnly=true（未配對、僅 traj）時無分析結果，值為 null。 */
            metrics: {
                /**
                 * @description 入射速度 (km/s)
                 * @example 42.7
                 */
                entrySpeed: number | null;
                /**
                 * @description 峰值視星等 (mag)，數值越小越亮
                 * @example -3.2
                 */
                peakMagnitude: number | null;
                /**
                 * @description 輻射點方位角 (degree)
                 * @example 215.5
                 */
                radiantAzimuth: number | null;
                /**
                 * @description 發光起點高度 (km)
                 * @example 98.4
                 */
                beginHeight: number | null;
                /**
                 * @description 發光終點高度 (km)
                 * @example 82.1
                 */
                endHeight: number | null;
                /**
                 * @description 終點地心座標 X (km)，東向（3D 向量 [0]）
                 * @example 12.5
                 */
                terminalPointX: number | null;
                /**
                 * @description 終點地心座標 Y (km)，北向（3D 向量 [1]；單站解算時可為 null）
                 * @example 0
                 */
                terminalPointY: number | null;
                /**
                 * @description 終點地心座標 Z (km)，高度方向（3D 向量 [2]）(#86 新增)
                 * @example 75.3
                 */
                terminalPointZ: number | null;
                /**
                 * @description 入射傾角 (degree)，負值代表向下 (#86 新增)
                 * @example -5.8
                 */
                entryAngle: number | null;
                /**
                 * @description 水平方位角 (degree) (#86 新增)
                 * @example 1.2
                 */
                azimuthAngle: number | null;
                /**
                 * @description 減速度垂直分量 (km/s²) (#86 新增)
                 * @example 3.1
                 */
                decelVertical: number | null;
                /**
                 * @description 減速度水平分量 (km/s²) (#86 新增)
                 * @example -1.4
                 */
                decelHorizontal: number | null;
                /**
                 * @description 光度曲線偏度 (0.0–1.0) (#86 新增)
                 * @example 0.92
                 */
                lightCurveSkew: number | null;
                /**
                 * @description 測光質量 (mg) (#86 新增)
                 * @example 2050
                 */
                photometricMass: number | null;
                /**
                 * @description 天頂角 (degree) (#86 新增)
                 * @example 18.5
                 */
                zenithAngle: number | null;
            };
            media: {
                /**
                 * @description 影片非同步處理狀態 (processing:處理中, ready:已就緒, failed:失敗)
                 * @example processing
                 * @enum {string}
                 */
                videoStatus: "processing" | "ready" | "failed";
                /**
                 * Format: uri
                 * @description 主站視角 MP4 影片路徑（處理中為 null，就緒後由 Nginx 服務）
                 * @example https://media.example.org/videos/watches/uuid123/primary.mp4
                 */
                primaryVideoUrl: string | null;
                /**
                 * Format: uri
                 * @description 副站視角 MP4 影片路徑（處理中為 null，就緒後由 Nginx 服務）
                 * @example https://media.example.org/videos/watches/uuid123/secondary.mp4
                 */
                secondaryVideoUrl: string | null;
            };
            /**
             * @description 即時天球分區圖 (sky grid) 圖片，base64 PNG 的 data URI
             *     （`data:image/png;base64,...`，可直接放入 `<img src>`）。後端依觀測站緯度
             *     (observer_lat) 與終點座標即時呼叫外部星圖服務取得 (#86)。外部服務逾時/失敗、
             *     或該事件尚無終點座標（無 analyze 結果）時降級為 null，不影響單筆詳情其餘欄位回傳。
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUg...
             */
            skyChart: string | null;
            /**
             * @description 星圖服務的雙站確認判定 (#86)。與 skyChart 同源：外部服務逾時/失敗、或該事件
             *     尚無終點座標時降級為 null。
             * @example true
             */
            isConfirmed: boolean | null;
        };
        StreamResponse: {
            /** Format: uuid */
            streamId: string;
            /** @example 主站全天相機直播 */
            name: string;
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "inactive" | "error";
            /**
             * Format: uri
             * @example https://stream.example.org/live/cam1/index.m3u8
             */
            hlsUrl: string;
            /** Format: date-time */
            createdAt: string;
        };
        SseEventEnvelope: {
            /**
             * @description 事件唯一識別碼（uuid hex）
             * @example 3f2a1b4c5d6e7f8090a1b2c3d4e5f607
             */
            id: string;
            /**
             * @description 事件類型，前端依此分流
             * @enum {string}
             */
            type: "connected" | "sightingCreated" | "watchCaptureStarted" | "watchCaptureStopped";
            /**
             * @description 來源頻道，`account:{accountId}` 或 `watch:{watchId}`
             * @example watch:6f1d2c34-0000-0000-0000-000000000000
             */
            channel: string;
            /**
             * Format: date-time
             * @description 事件時間（UTC，秒級精度，`...Z` 結尾）
             */
            timestamp: string;
            /** @description 事件酬載（camelCase）。connected：{ channels: [...] }；sightingCreated：{ sightingId, watchId }； watchCaptureStarted / watchCaptureStopped：{ watchId }。 */
            data: Record<string, never>;
        };
        /** @description v2 契約（#86）。額外欄位（裝置端舊版計算欄位等）寬鬆接收，僅存入完整原始 payload JSONB，不拆欄。 */
        TrajRawPayload: {
            /**
             * @description naive datetime 字串，一律視為 UTC+8 牆鐘時間（不得帶時區 offset）， 後端轉為 UTC 儲存。支援 `T` 與空格兩種分隔、最高微秒精度。 為冪等鍵：相同 timestamp 重送視為同一筆目擊事件。traj 與 photo 須使用 同一時間基準以確保 2 秒配對窗正確。
             * @example 2026-06-05T14:30:00.123456
             */
            timestamp: string;
            /**
             * @description 3D 原始軌跡點列表，每點為 `[x, y, z, t_rel]` 四元素陣列（t_rel 為相對軌跡起點的秒數）
             * @example [
             *       [
             *         0.1,
             *         18.4,
             *         1.8,
             *         0
             *       ],
             *       [
             *         0.05,
             *         14.2,
             *         1.6,
             *         0.1
             *       ]
             *     ]
             */
            raw_traj: number[][];
            /**
             * @description 軌跡起點相對時間（秒）
             * @example 0
             */
            traj_start_ts: number;
            /**
             * @description 軌跡終點相對時間（秒）
             * @example 0.46
             */
            traj_end_ts: number;
            /** @description X 軸二次擬合係數 c0（f(t) = c0 + c1*t + c2*t²；Y、Z 軸同形） */
            path_traj_Xc0: number;
            path_traj_Xc1: number;
            path_traj_Xc2: number;
            path_traj_Yc0: number;
            path_traj_Yc1: number;
            path_traj_Yc2: number;
            path_traj_Zc0: number;
            path_traj_Zc1: number;
            path_traj_Zc2: number;
        };
        /** @description v2 契約（#86）。額外欄位寬鬆接收，僅存入完整原始 payload JSONB，不拆欄。 */
        PhotoRawPayload: {
            /**
             * @description naive datetime 字串，一律視為 UTC+8 牆鐘時間（不得帶時區 offset）， 後端轉為 UTC 儲存。支援 `T` 與空格兩種分隔、最高微秒精度。 為冪等鍵：相同 timestamp 重送視為同一筆目擊事件。須與 traj 使用同一 時間基準以確保 2 秒配對窗正確。
             * @example 2026-06-05 14:30:00.223456
             */
            timestamp: string;
            /**
             * @description 輻射點單位向量 `[x, y, z]`，後端拆解為 radiantX/radiantY/radiantZ 儲存
             * @example [
             *       1,
             *       0,
             *       0
             *     ]
             */
            radiant: number[];
            /**
             * @description 峰值視星等 (mag)
             * @example -3.2
             */
            peak_mag: number;
            /** @description 輻射點赤經（時分表示法 + 角度） */
            radiant_ra: {
                /** @example 12:00 */
                hhmm: string;
                /** @example 0 */
                degrees: number;
            };
            /** @description 中天時刻（時分表示法 + 角度） */
            culmination: {
                /** @example 12:00 */
                hhmm: string;
                /** @example 0 */
                degrees: number;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description 頁碼，從 1 開始 */
        pageParam: number;
        /** @description 每頁筆數，預設 20，最大限制 100 */
        pageSizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
